logging:
  file: /home/work/jpaas_light_collector/log/collector.log

mysql:
  host: 10.36.58.31
  username: jpaas
  password: mhxzkhl
  db_name: jpaas

cluster_mysql:
  host: 10.23.247.41
  username: root
  password: jpaasv2-ci
  db_name: JPaaSV2_hosts
  port: 7777
listen_port: 8003
